Replace `relative_path` with `name` as the mandatory entry when registering datasets
LSSTDESC/dataregistry pull request #136
Opened 2024-08-05 13:30 UTC by stuartmcalpine

This supersedes the old pull request.

Replace `relative_path` with `name` as the mandatory quantity when registering datasets. Users can still specify a manual `relative_path` during registration if requested. If no `relative_path` is given, one is generated automatically from the name and version.

When overwriting datasets, users must provide the `name` and `relative_path` for the entry they wish to overwrite.

2024-08-05 21:15 UTC, JoanneBogart requested changes
It looks good overall.  There is one thing that has to be fixed - I think a block of code just has to be moved upwards a little bit - and one harmless typo in a docstring.

2024-08-06 15:04 UTC, stuartmcalpine commented on src/dataregistry/registrar/dataset.py
> +        # If `relative_path` not passed, automatically generate it
Ah, good spot. Also had to then move the version bumping up aswell

2024-08-06 15:05 UTC, stuartmcalpine commented on tests/end_to_end_tests/database_test_utils.py
> +        name, dataset_id, ref_alias_id=ref_alias_id, supersede=supersede
Changed

2024-08-06 15:06 UTC, stuartmcalpine commented on tests/end_to_end_tests/test_cli.py
> +            ["dataset.name", "dataset.version_string"], [f]
Ah, this was just because there was no actual test using relative path here, so there was no need to return it

2024-08-06 18:52 UTC, JoanneBogart commented
@stuartmcalpine Looks like all my comments have been addressed.  Would you like me to re-review?

2024-08-06 19:32 UTC, stuartmcalpine commented
> @stuartmcalpine Looks like all my comments have been addressed. Would you like me to re-review?

Yes, was just amending the docs, now ready

2024-08-06 20:51 UTC, JoanneBogart approved these changes
LGTM

2024-08-06 21:10 UTC, merged