U/jrbogart/gcr tutorial
LSSTDESC/dataregistry pull request #166
Opened 2024-11-11 18:46 UTC by JoanneBogart

Demonstrate querying and accessing GCRCatalog-type catalogs via dataregistry.

2025-01-17 00:20 UTC, stuartmcalpine commented
Overall I think it's fine. It won't continue to work as-is with the new changes to the connection to the production schema etc, so the mechanics will have to change a bit.

Also need to add a link to the note book in the docs somewhere. Do we want a page in the docs for this? (or for DESC specific applications of the registry)

2025-01-23 21:09 UTC, JoanneBogart commented
Why won't the code here work as is?   The connection to dataregistery happens with
`GCRCatalogs.ConfigSource.set_config_source(dr=True)`

which ultimately makes a connection with
`dr_reg = DataRegistry(schema=dr_schema, root_dir=dr_root, site=dr_site)`

where dr_schema is "lsst_desc_production"
It would be better if that value were obtained from `schema.DEFAULT_SCHEMA_PRODUCTION` rather than hard-coded as it is currently, but I think it will do the right thing.  Or am I missing something?

Yes, there should be a link to the notebook somewhere. It looks like `tutorial_python.rst` would be the right place. I'll add that.

2025-01-29 19:10 UTC, stuartmcalpine requested changes
This looks like it should work. Need to double check testing it with the other PR.

Only comments relate to changes other PR will make relating to the schema to connect to

2025-01-29 19:10 UTC, stuartmcalpine commented on docs/source/tutorial_notebooks/query_gcr_datasets.ipynb
> +    "\n",
There is no `DEFAULT_SCHEMA_PRODUCTION` anymore.

Options would be 
- Import `DEFAULT_NAMESPACE` and connect to `schema=f"{DEFAULT_NAMESPACE}_production"`
- Specify or not the `DEFAULT_NAMESPACE` (but no need), and choose `query_mode="production"` to limit queries to production schema

2025-01-29 19:10 UTC, stuartmcalpine commented on docs/source/tutorial_notebooks/query_gcr_datasets.ipynb
> +    "Recall that a `DataRegistry` instance has a member `Query` which provides all the query services, the principal one being the ability to ask for values of attributes of datasets, subject to one
The query getting started is now "Part 2"

2025-01-29 20:11 UTC, stuartmcalpine approved these changes

2025-01-29 20:13 UTC, merged