Update tutorial docs
LSSTDESC/dataregistry pull request #61
Opened 2023-09-04 14:08 UTC by stuartmcalpine

Updated the docs to now match with the tutorial notebooks.

Also updated the CLI docs to include `dregs ls`

2023-09-13 22:09 UTC, JoanneBogart requested changes
Generally looks good but there are some things which should be addressed.

2023-09-13 22:09 UTC, JoanneBogart commented on docs/source/tutorial_notebooks/getting_started.ipynb
> +    "If you haven't done so already, check out the [getting setup](file:///home/mcalpine/Documents/dataregistry/dataregistry/docs/build/html/tutorial_setup.html) page from the docs if you want to run
I don't think you want a reference to what looks like a local file on your machine.

2023-09-13 22:09 UTC, JoanneBogart commented on docs/source/tutorial_notebooks/pipline_datasets.ipynb
> +    "If you haven't done so already, check out the [getting setup](file:///home/mcalpine/Documents/dataregistry/dataregistry/docs/build/html/tutorial_setup.html) page from the docs if you want to run
Same comment as above: this appears to be referencing a file on your local machine.

2023-09-13 22:09 UTC, JoanneBogart commented on docs/source/tutorial_notebooks/pipline_datasets.ipynb
> +    "This tutorial focuses on how to register data into `DREGS` from a\n",
Did you really mean to call this notebook "pipline_datasets.ipynb"?   I would change to "pipeline_datasets.ipynb".

2023-09-18 08:00 UTC, stuartmcalpine commented on docs/source/tutorial_notebooks/getting_started.ipynb
> +    "# Getting started with **DREGS**\n",
I've removed all the output for now.

Will have a look to see how best to do rendered versions.

2023-09-19 16:40 UTC, JoanneBogart approved these changes
Looks fine now.
I think we'll have to redo the logo without "DREGS", but that can be in a separate PR.

2023-09-20 06:06 UTC, merged