Refactor registrar into multiple files
LSSTDESC/dataregistry pull request #92
Opened 2024-01-09 12:24 UTC by stuartmcalpine

In preparation for us doing more with entries other than creating them, I've reformatted the registrar class into one for each table, e.g., dataset, execution and dataset_alias.

As before they all follow the same format with a slight tweak. e.g., `datareg.Registrar.register_dataset()` now becomes `datareg.Registrar.dataset.create()` and `datareg.Registrar.execution.create()` etc.

This is in preparation for new functions like `datareg.Registrar.dataset.modify()` or `datareg.Registrar.dataset.delete()` etc. 

It also tidies the code a bit (mainly in prep for the new functions) so that `registrar.py` didn't become very long.

2024-01-18 00:20 UTC, JoanneBogart requested changes
I've suggested a couple specific and simple changes, but additionally we should probably think a little more about the organization.   One possibility would be to make a base class - call it `RegistryTable` for now - which your new classes would subclass. `RegistryTable` would have base implementations for at least `modify` and `delete`. `register` is generally more complicated and different from one table to the next, so perhaps `RegistryTable.register( )` would always have to be overridden by the subclass.   To the extent that the different tables need, even partially, the same treatment, the base class would be a convenient place to put the common parts of the implementations.

2024-01-26 13:02 UTC, stuartmcalpine commented on src/dataregistry/registrar/execution.py
> +    def create(
Yes I agree. I've changed all the functions to `register`

2024-01-26 13:06 UTC, stuartmcalpine commented on src/dataregistry/registrar/execution.py
> +    def delete(self):
I have updated the placeholders

2024-01-26 13:16 UTC, stuartmcalpine commented
I have updated the structure as suggested. Now there is a base table class which the execution/dataset/etc tables will inherit. The base class holds the `delete` and `modify` function as they should be universal.

The `register` (renamed from `create`) functions are in each of their own subclasses.

The only slightly dirty bit is that I have to pass the execution subclass into the dataset subclass in the `Registrar` class. Thats because we need to create an execution from within the dataset registration also. But I dont see a way around it.

2024-02-07 22:40 UTC, JoanneBogart approved these changes
It looks good to me.  I made one trivial comment.

2024-02-07 22:40 UTC, JoanneBogart commented on tests/end_to_end_tests/test_end_to_end.py
> +#from dataregistry.registrar import get_owner_types
Can we get rid of this line altogether?

2024-03-07 11:13 UTC, merged